apiVersion: v1
kind: Service
metadata:
  name: java-service
  labels:
    demo: networking
spec:
  selector:
    app: java-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080