apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: stateful-java-service
  name: stateful-java-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful-java-service
  serviceName: stateful-java-service
  template:
    metadata:
      labels:
        app: stateful-java-service
    spec:
      containers:
        - name: stateful-java-service
          image: javaguildkubernetes/java-service:volumes
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: data
      serviceAccountName: default
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 64Mi