apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service-deployment
  labels:
    app: java-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
        - name: java-service
          image: javaguildkubernetes/java-service:configmap
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: my-config
              mountPath: /app/resources/application-kubernetes.yaml
              subPath: application-kubernetes.yaml
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
          envFrom:
            - secretRef:
                name: java-service-secret
      volumes:
        - name: my-config
          configMap:
            name: java-service-configmap